### ISSUE TITLE
Uberdog log error

### ISSUE THREAD

**Issue by danielchicote** [magento-hackathon/Hackathon_MageMonitoring#37]
Uberdog always gives me this error in the logs and i dont understand it:

[01-Sep-2015 21:35:02 UTC] PHP Notice:  Undefined index: SCRIPT_FILENAME in /home/magento/public_html/app/code/core/Mage/Core/Model/Store.php on line 643

Can someone tell me something about this? Thanks

**Comment by edannenberg** [comment]
On first glance this looks unrelated. What Magento version? To ensure it's actually caused by MageMonitoring please setup a vanilla Magento and try again.

**Comment by rogyar** [comment]
Hello Guys. The issue is not connected to current extension. The reason is the global environment variable `$_SERVER['SCRIPT_FILENAME']` is not allowed in your server's configuration. As edannenberg said, if you provide more information about your Magento version and PHP version as well - we might have more suggestions about the issue.

**Comment by edannenberg** [comment]
Closing this as it seems to be a drive-by ticket.
